# Generated by Django 2.1.1 on 2018-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='room_no',
        ),
        migrations.AddField(
            model_name='transactions',
            name='no_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='rooms_allocated',
            field=models.ManyToManyField(to='booking.Rooms'),
        ),
    ]
