# Generated by Django 2.1.2 on 2018-10-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Single AC', 'Single AC'), ('Double AC', 'Double AC'), ('Single NON AC', 'Single NON AC'), ('Double NON AC', 'Double NON AC')], max_length=20)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.GuestHouse')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Rooms')),
                ('user_booked', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
