# Generated by Django 2.1.2 on 2018-10-06 15:01

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rooms_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=booking.models.get_image_path)),
            ],
        ),
    ]
