# Generated by Django 2.1.2 on 2018-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_extendeduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
