# Generated by Django 2.1.1 on 2018-10-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_transactions_guesthouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetails',
            name='room',
        ),
    ]
