# Generated by Django 2.1.2 on 2018-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20181006_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
