# Generated by Django 2.1.2 on 2018-10-08 13:30

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20181006_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='no_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=booking.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
