# Generated by Django 2.1.1 on 2018-10-18 15:01

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20181017_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(blank=True, default='users/no.png', null=True, upload_to=booking.models.get_image_path),
        ),
    ]
