# Generated by Django 2.1.1 on 2018-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20181017_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
