# Generated by Django 2.1.1 on 2018-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20181018_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date_book',
            field=models.DateField(blank=True, null=True),
        ),
    ]
