# Generated by Django 2.1.1 on 2018-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_transactions_date_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
