# Generated by Django 2.1.1 on 2018-11-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_transactions_transaction_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_people', models.IntegerField(blank=True, null=True)),
                ('no_people_done', models.IntegerField(blank=True, default=0, null=True)),
                ('no_rooms', models.IntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='no_people_done',
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='next_transaction_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pretransactions',
            name='guesthouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.GuestHouse'),
        ),
    ]
